categories:
  - title: ':memo: Changes in the contracts'
    label: 'contracts'
  - title: ':rocket: Changes in the client'
    label: 'client'
  - title: ':bug: BugFix'
    label: 'bugfix'
version-resolver:
  default: minor
prerelease: true
template: |
  ## What’s Changed

  $CHANGES
